vim.keymap.set("n", "<Esc>", ":nohl<CR>", { silent = true })
vim.keymap.set("n", "<leader>w", ":write<CR>", { silent = true })
vim.keymap.set("n", "<leader>q", ":quit<CR>", { silent = true })
vim.keymap.set("n", "<leader>L", "<cmd>Lazy<CR>")

vim.keymap.set("n", "<leader>r", function()
  require("conform").format({ async = true })
end)

vim.keymap.set("n", "<leader>e", function()
  require("snacks").explorer()
end, { silent = true })
vim.keymap.set("n", "<leader>f", function()
  require("snacks").picker.files()
end)
vim.keymap.set("n", "<leader>F", function()
  require("snacks").picker.grep()
end)
vim.keymap.set("n", "<leader>gw", function()
  require("snacks").picker.grep_word()
end)
vim.keymap.set("n", "]w", function()
  require("snacks").words.jump(1)
end)
vim.keymap.set("n", "[w", function()
  require("snacks").words.jump(-1)
end)
vim.keymap.set("n", "<leader>b", function()
  require("snacks").picker.buffers()
end)
vim.keymap.set("n", "<leader>d", function()
  require("snacks").picker.diagnostics()
end)
vim.keymap.set("n", "<leader>u", function()
  require("snacks").picker.undo()
end)
vim.keymap.set("n", "<leader>gb", function()
  require("snacks").picker.git_branches()
end)
vim.keymap.set("n", "<leader>gs", function()
  require("snacks").picker.git_status()
end)
vim.keymap.set("n", "<leader>gc", function()
  require("snacks").picker.git_commits()
end)
vim.keymap.set("n", "<leader>n", function()
  require("snacks").picker.notifications()
end)
vim.keymap.set("n", "<leader>sq", function()
  require("snacks").picker.qflist()
end)

vim.keymap.set("n", "gd", function()
  require("snacks").picker.lsp_definitions()
end)
vim.keymap.set("n", "gD", function()
  require("snacks").picker.lsp_declarations()
end)
vim.keymap.set("n", "gr", function()
  require("snacks").picker.lsp_references()
end)
vim.keymap.set("n", "gI", function()
  require("snacks").picker.lsp_implementations()
end)
vim.keymap.set("n", "gy", function()
  require("snacks").picker.lsp_type_definitions()
end)
vim.keymap.set("n", "gai", function()
  require("snacks").picker.lsp_incoming_calls()
end)
vim.keymap.set("n", "gao", function()
  require("snacks").picker.lsp_outgoing_calls()
end)
vim.keymap.set("n", "<leader>ss", function()
  require("snacks").picker.lsp_symbols()
end)
vim.keymap.set("n", "<leader>sS", function()
  require("snacks").picker.lsp_workspace_symbols()
end)

vim.keymap.set("n", "[d", function()
  vim.diagnostic.goto_prev({ float = true })
end)
vim.keymap.set("n", "]d", function()
  vim.diagnostic.goto_next({ float = true })
end)

vim.keymap.set("n", "<leader>z", function()
  require("snacks").zen()
end)
vim.keymap.set("n", "<leader>ca", function()
  require("actions-preview").code_actions()
end)

vim.keymap.set({ "i", "s" }, "<C-e>", function()
  require("luasnip").expand_or_jump(1)
end, { silent = true })
vim.keymap.set({ "i", "s" }, "<C-J>", function()
  require("luasnip").jump(1)
end, { silent = true })
vim.keymap.set({ "i", "s" }, "<C-K>", function()
  require("luasnip").jump(-1)
end, { silent = true })

vim.keymap.set("n", "<leader>ih", function()
  vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled({ 0 }))
end)

vim.keymap.set("n", "<leader>sv", ":vsplit<CR>", { silent = true })
vim.keymap.set("n", "<leader>sh", ":split<CR>", { silent = true })
vim.keymap.set("n", "K", vim.lsp.buf.hover)
vim.keymap.set("n", "Q", "<nop>")
vim.keymap.set("n", "j", "gj")
vim.keymap.set("n", "k", "gk")
vim.keymap.set("n", "<C-h>", "<C-w>h")
vim.keymap.set("n", "<C-j>", "<C-w>j")
vim.keymap.set("n", "<C-k>", "<C-w>k")
vim.keymap.set("n", "<C-l>", "<C-w>l")
vim.keymap.set("i", "jj", "<Esc>")
vim.keymap.set("v", ">", ">gv")
vim.keymap.set("v", "<", "<gv")
