local keymap = vim.keymap.set
local opts = { noremap = true, silent = true }

keymap("n", "<leader><space>", ":noh<CR>", { desc = "Clear search highlights", noremap = true, silent = true })
keymap("n", "<leader>w", ":w<CR>", { desc = "Save file", noremap = true, silent = true })
keymap("n", "<leader>q", ":q<CR>", { desc = "Quit", noremap = true, silent = true })
keymap("n", "<C-h>", "<C-w>h", { desc = "Window left", noremap = true, silent = true })
keymap("n", "<C-j>", "<C-w>j", { desc = "Window down", noremap = true, silent = true })
keymap("n", "<C-k>", "<C-w>k", { desc = "Window up", noremap = true, silent = true })
keymap("n", "<C-l>", "<C-w>l", { desc = "Window right", noremap = true, silent = true })
keymap("n", "<leader>sv", ":vsplit<CR>", { desc = "Vertical split", noremap = true, silent = true })
keymap("n", "<leader>sh", ":split<CR>", { desc = "Horizontal split", noremap = true, silent = true })
keymap("n", "j", "gj", { desc = "Move down (display)", noremap = true, silent = true })
keymap("n", "k", "gk", { desc = "Move up (display)", noremap = true, silent = true })
keymap("n", "Q", "<nop>", { desc = "Disable Q", noremap = true, silent = true })

keymap("n", "<leader>ff", function()
  require("telescope.builtin").find_files()
end, { desc = "Find files", noremap = true, silent = true })
keymap("n", "<leader>fg", function()
  require("telescope.builtin").live_grep()
end, { desc = "Live grep", noremap = true, silent = true })
keymap("n", "<leader>fb", function()
  require("telescope.builtin").buffers()
end, { desc = "Find buffers", noremap = true, silent = true })
keymap("n", "<leader>ft", function()
  require("telescope.builtin").treesitter()
end, { desc = "Find treesitter", noremap = true, silent = true })

keymap("n", "<leader>e", ":NvimTreeToggle<CR>", { desc = "Toggle file tree", noremap = true, silent = true })
keymap("n", "<leader>=", function()
  require("conform").format()
end, { desc = "Format code", noremap = true, silent = true })
