require("nvim-treesitter.configs").setup({
  ensure_installed = {
    "lua",
    "rust",
    "zig",
    "c",
    "cpp",
    "xml",
    "typst",
    "markdown",
    "markdown_inline",
    "vim",
    "vimdoc",
    "json",
    "yaml",
    "toml",
  },
  sync_install = false,
  auto_install = true,
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
  indent = { enable = true },
})
